server:
  port: ${port:9899}
  servlet:
    context-path: /
spring:
  application:
    name: jarboot-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  jmx:
    default-domain: jarboot-server
  jms:
    pub-sub-domain: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 512MB
      max-request-size: 512MB
  profiles:
    active: @env@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    driver-class-name: ${jarboot.db.driverClassName:org.apache.derby.jdbc.EmbeddedDriver}
    url: ${jarboot.db.url:jdbc:derby:${JARBOOT_HOME}/data/derby_data;create=true}
    username: ${jarboot.db.user:root}
    password: ${jarboot.db.password:jarboot4iLCJleHAiOjE3MDI5}
    hikari:
      minimum-idle: 2
      pool-name: jarboot_db_pool
  quartz:
    job-store-type: jdbc